spring:
  data:
    mongodb:
      database: book

  shell:
    interactive:
      enabled: true
  main:
    allow-circular-references: true


mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.zav.storedbooksinfo.changelog

logging:
  level:
    root: ERROR