
--Жанры
DROP TABLE GENRE IF EXISTS;
CREATE TABLE GENRE(
    ID VARCHAR(36) PRIMARY KEY,
    DESCRIPTION VARCHAR(256)
);

-- Авторы
DROP TABLE AUTHOR IF EXISTS;
CREATE TABLE AUTHOR(
    ID VARCHAR(36) PRIMARY KEY,
    FIRST_NAME VARCHAR(64),
    LAST_NAME VARCHAR(64),
    FAMILY_NAME VARCHAR(64)
);

DROP TABLE BOOK IF EXISTS;
CREATE TABLE BOOK(
    id VARCHAR(36) PRIMARY KEY,
    TITLE VARCHAR(256),
    GENRE_ID VARCHAR(36),
    AUTHORS_SET_ID VARCHAR(36)
);

--Жанры
DROP TABLE AUTHORS_SET IF EXISTS;
CREATE TABLE AUTHORS_SET(
    id VARCHAR(36) PRIMARY KEY,
    AUTHORS_SET_ID VARCHAR(36),
    AUTHOR_ID VARCHAR(36)
);


create table BOOK_AUTHOR(
    BOOK_ID VARCHAR(36) references BOOK(ID) ON DELETE CASCADE,
    AUTHOR_ID VARCHAR(36) references AUTHOR(ID) ON DELETE CASCADE,
    primary key (BOOK_ID, AUTHOR_ID)
);