DROP TABLE BOOK IF EXISTS;
CREATE TABLE BOOK(id BIGINT PRIMARY KEY, TITLE VARCHAR(256), GENRE_ID BIGINT, AUTHORS_SET_ID BIGINT);

--Жанры
DROP TABLE GENRE IF EXISTS;
CREATE TABLE GENRE(id BIGINT PRIMARY KEY, GENRE_DESCRIPTION VARCHAR(256));

-- Авторы
DROP TABLE AUTHOR IF EXISTS;
CREATE TABLE AUTHOR(id BIGINT PRIMARY KEY, FIRST_NAME VARCHAR(64), LAST_NAME VARCHAR(64), FAMILY_NAME VARCHAR(64));

--Жанры
DROP TABLE AUTHORS_SET IF EXISTS;
CREATE TABLE AUTHORS_SET(id BIGINT PRIMARY KEY, AUTHORS_SET_ID BIGINT, AUTHOR_ID BIGINT);