spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
      data-locations: classpath:/test-data.sql
      schema-locations: classpath:/schema.sql

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: false

    properties:
      hibernate:
        format_sql: true


  shell:
    interactive:
      enabled: false

  main:
    allow-circular-references: true

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

logging:
  level:
    root: ERROR